# Файл конфигурации системы управления

# Коэффициенты ПИД регулятора угловой скорости по оси X
KpXAngularRate: 6
KiXAngularRate: 0
KdXAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Y
KpYAngularRate: 10
KiYAngularRate: 0
KdYAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Z
KpZAngularRate: 0.25
KiZAngularRate: 0
KdZAngularRate: 0
# Коэффициенты ПИД регулятора углового положения по оси X
KpXAngle: 0
KiXAngle: 0
KdXAngle: 0
# Коэффициенты ПИД регулятора углового положения по оси Y
KpYAngle: 0
KiYAngle: 0
KdYAngle: 0
# Коэффициенты ПИД регулятора углового положения по оси Z
KpZAngle: 0
KiZAngle: 0
KdZAngle: 0
# Коэффициенты ПИД регулятора пространственного положения по оси X
KpXPosition: 325
KiXPosition: 150
KdXPosition: 240
# Коэффициенты ПИД регулятора пространственного положения по оси Y
KpYPosition: 325
KiYPosition: 150
KdYPosition: 240
# Коэффициенты ПИД регулятора пространственного положения по оси Z
KpZPosition: 325
KiZPosition: 137
KdZPosition: 263

# Ограничение значений выхода ПИД-регулятора по угловому положению
maxCommandAngle: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловой скорости
maxCommandAngularRate: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловому ускорению
maxCommandAngularAcceleration: 0
# Ограничение по тяге
maxThrust: 0