# Файл конфигурации системы управления

# Коэффициенты ПИД регулятора угловой скорости по оси X
KpXAngularRate: 1
KiXAngularRate: 2
KdXAngularRate: 3
# Коэффициенты ПИД регулятора угловой скорости по оси Y
KpYAngularRate: 4
KiYAngularRate: 5
KdYAngularRate: 6
# Коэффициенты ПИД регулятора угловой скорости по оси Z
KpZAngularRate: 7
KiZAngularRate: 8
KdZAngularRate: 9
# Коэффициенты ПИД регулятора углового положения по оси X
KpXAngle: 0
KiXAngle: 0
KdXAngle: 0
# Коэффициенты ПИД регулятора углового положения по оси Y
KpYAngle: 0
KiYAngle: 0
KdYAngle: 0
# Коэффициенты ПИД регулятора углового положения по оси Z
KpZAngle: 0
KiZAngle: 0
KdZAngle: 0
# Коэффициенты ПИД регулятора пространственного положения по оси X
KpXPosition: 1
KiXPosition: 1
KdXPosition: 1
# Коэффициенты ПИД регулятора пространственного положения по оси Y
KpYPosition: 1
KiYPosition: 1
KdYPosition: 1
# Коэффициенты ПИД регулятора пространственного положения по оси Z
KpZPosition: 1
KiZPosition: 1
KdZPosition: 1

# Ограничение значений выхода ПИД-регулятора по угловому положению
maxCommandAngle: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловой скорости
maxCommandAngularRate: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловому ускорению
maxCommandAngularAcceleration: 0
# Ограничение по тяге
maxThrust: 0