# Файл конфигурации системы управления

# Коэффициенты ПИД регулятора угловой скорости по оси X
KpXAngularRate: 5
KiXAngularRate: 0.5
KdXAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Y
KpYAngularRate: 5
KiYAngularRate: 0.5
KdYAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Z
KpZAngularRate: 3000
KiZAngularRate: 100
KdZAngularRate: 0
# Коэффициенты ПИД регулятора углового положения по оси X
KpXAngle: 325
KiXAngle: 150
KdXAngle: 240
# Коэффициенты ПИД регулятора углового положения по оси Y
KpYAngle: 325
KiYAngle: 150
KdYAngle: 240
# Коэффициенты ПИД регулятора углового положения по оси Z
KpZAngle: 325
KiZAngle: 150
KdZAngle: 240
# Коэффициенты ПИД регулятора пространственного положения по оси X
KpXPosition: 325
KiXPosition: 150
KdXPosition: 240
# Коэффициенты ПИД регулятора пространственного положения по оси Y
KpYPosition: 325
KiYPosition: 150
KdYPosition: 240
# Коэффициенты ПИД регулятора пространственного положения по оси Z
KpZPosition: 325
KiZPosition: 150
KdZPosition: 240

# Ограничение значений выхода ПИД-регулятора по угловому положению
maxCommandAngle: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловой скорости
maxCommandAngularRate: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловому ускорению
maxCommandAngularAcceleration: 0
# Ограничение по тяге
maxThrust: 0