# Файл конфигурации системы управления

# Коэффициенты ПИД регулятора угловой скорости по оси X
KpXAngularRate: 6
KiXAngularRate: 0
KdXAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Y
KpYAngularRate: 10
KiYAngularRate: 0
KdYAngularRate: 0
# Коэффициенты ПИД регулятора угловой скорости по оси Z
KpZAngularRate: 0.25
KiZAngularRate: 0
KdZAngularRate: 0
# Коэффициенты ПИД регулятора углового положения по оси X
KpXAngle: 10
KiXAngle: 1
KdXAngle: 2
# Коэффициенты ПИД регулятора углового положения по оси Y
KpYAngle: 10
KiYAngle: 1
KdYAngle: 2
# Коэффициенты ПИД регулятора углового положения по оси Z
KpZAngle: 10
KiZAngle: 0
KdZAngle: 0
# Коэффициенты ПИД регулятора пространственного положения по оси X
KpXPosition: 0.65
KiXPosition: 0.001
KdXPosition: 1.15
# Коэффициенты ПИД регулятора пространственного положения по оси Y
KpYPosition: 0.65
KiYPosition: 0.01
KdYPosition: 0.95
# Коэффициенты ПИД регулятора пространственного положения по оси Z
KpZPosition: 325
KiZPosition: 137
KdZPosition: 263

# Ограничение значений выхода ПИД-регулятора по угловому положению
maxCommandAngle: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловой скорости
maxCommandAngularRate: 0
# Ограничения максимального значения выхода ПИД-регулятора по угловому ускорению
maxCommandAngularAcceleration: 0
# Ограничение по тяге
maxThrust: 0